name: Update Fork

on:
  schedule:
    - cron: "0 0 * * *" # Roda diariamente à meia-noite (UTC)
  workflow_dispatch: # Permite rodar manualmente

jobs:
  update-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up git
        run: |
          git config --global user.email "alexandrefersoa@gmail.com"
          git config --global user.name "Alexandre Niess"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/sabarense/eco_guia

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main

      - name: Push changes
        run: git push origin main
