name: Update Fork

on:
  schedule:
    - cron: "0 0 * * *" # Roda diariamente à meia-noite (UTC)
  workflow_dispatch: # Permite rodar manualmente

jobs:
  update-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master  # Certifique-se de estar na branch master do fork

      - name: Set up git
        run: |
          git config --global user.email "alexandrefersoa@gmail.com"
          git config --global user.name "Alexandre Niess"

      - name: Verificar remotes existentes
        run: git remote -v  # Verificar se upstream já está configurado

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/sabarense/eco_guia || true
          git remote -v  # Re-verificar para garantir que upstream foi adicionado

      - name: Fetch upstream
        run: |
          git fetch upstream  # Traz as atualizações do repositório original
          git fetch --all  # Garante que todas as branches sejam trazidas

      - name: Verificar branch local
        run: |
          git checkout master  # Garante que estamos na branch master
          git branch -a  # Exibe todas as branches disponíveis para verificação

      - name: Merge upstream/master into local master
        run: |
          git merge upstream/master --no-edit  # Faz o merge das mudanças da master do upstream
          git status  # Verifica se o merge foi bem-sucedido

      - name: Push changes to origin
        run: git push origin master  # Faz o push das mudanças para seu fork
