name: Update Fork

on:
  schedule:
    - cron: "0 0 * * *" # Roda diariamente à meia-noite (UTC)
  workflow_dispatch: # Permite rodar manualmente

jobs:
  update-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master  # Certifique-se de que estamos na branch master

      - name: Set up git
        run: |
          git config --global user.email "alexandrefersoa@gmail.com"
          git config --global user.name "Alexandre Niess"

      - name: Verificar repositórios remotos
        run: git remote -v  # Verificar se o upstream já está configurado corretamente

      - name: Add upstream repository
        run: git remote add upstream https://github.com/sabarense/eco_guia || true

      - name: Fetch upstream
        run: |
          git fetch upstream
          git branch -a  # Verificar as branches disponíveis

      - name: Verificar se a branch 'master' existe
        run: |
          if git show-ref --quiet refs/heads/master; then
            echo "Branch 'master' encontrada, trocando para 'master'"
            git checkout master
          else
            echo "Branch 'master' não encontrada, criando 'master'"
            git checkout -b master
          fi

      - name: Merge upstream changes
        run: |
          git merge upstream/master --no-commit || true
          if [ -n "$(git status --porcelain)" ]; then
            echo "Conflitos encontrados, merge incompleto."
            exit 1
          else
            echo "Merge realizado com sucesso."
          fi

      - name: Verificar estado após merge
        run: git status  # Verificar o estado atual do repositório após o merge

      - name: Push changes
        if: success()
        run: git push origin master
