name: Update Fork

on:
  schedule:
    - cron: "0 0 * * *"  # Roda diariamente à meia-noite (UTC)
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  update-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master  # Troca para a branch master do fork

      - name: Set up git
        run: |
          git config --global user.email "alexandrefersoa@gmail.com"
          git config --global user.name "Alexandre Niess"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/sabarense/eco_guia || true
          git remote -v  # Verifica se o remote upstream foi adicionado corretamente

      - name: Fetch upstream
        run: |
          git fetch upstream  # Traz todas as branches e commits do repositório original

      - name: Verificar se a branch 'master' existe localmente
        run: |
          git checkout master || git checkout -b master --track origin/master

      - name: Rebase master com upstream/master
        run: |
          git rebase upstream/master || exit 1  # Rebase dos commits do upstream/master no topo do fork

      - name: Push changes to origin
        run: |
          git push origin master --force-with-lease  # Faz push forçado com segurança para a master do fork
